"""Plan comptable standard : correspondance US GAAP <-> SYCEBNL.
Source : Correspondance_US_GAAP_SYCEBNL.xlsx (feuille « Correspondance »).
Ces lignes ne servent qu'à pré-remplir la base ; le plan reste modifiable dans l'application.
"""

STANDARD_CHART = [{'number': '1000',
  'name': 'Cash on hand',
  'syc_code': '571',
  'syc_name': 'Caisse en monnaie nationale',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'TRESORERIE'},
 {'number': '1010',
  'name': 'Petty cash',
  'syc_code': '571',
  'syc_name': 'Caisse en monnaie nationale',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'TRESORERIE'},
 {'number': '1100',
  'name': 'Cash in bank',
  'syc_code': '521',
  'syc_name': 'Banques locales',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'TRESORERIE'},
 {'number': '1110',
  'name': 'Foreign bank accounts',
  'syc_code': '524',
  'syc_name': 'Banques hors zone monétaire',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'TRESORERIE'},
 {'number': '1200',
  'name': 'Accounts receivable',
  'syc_code': '412',
  'syc_name': 'Clients-usagers',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'SYCEBNL : 411 = adhérents, 412 = clients-usagers. Utiliser 411 pour les cotisations ou créances '
            'sur adhérents.',
  'gaap_section': 'CA',
  'account_type': 'COMPTES_CLIENTS'},
 {'number': '1210',
  'name': 'Allowance for doubtful accounts',
  'syc_code': '491',
  'syc_name': 'Dépréciations des comptes adhérents et clients-usagers',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Compte de sens inverse (contra) : coefficient 1 à valider selon la logique de signe de '
            "l'intégration.",
  'gaap_section': 'CA',
  'account_type': 'AUTRE_ACTIF_CT'},
 {'number': '1300',
  'name': 'Notes receivable',
  'syc_code': '412',
  'syc_name': 'Clients-usagers',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Pas de compte dédié aux effets à recevoir dans la classe 41 du SYCEBNL (413 = effets impayés). '
            'Utiliser un sous-compte de 412.',
  'gaap_section': 'CA',
  'account_type': 'AUTRE_ACTIF_CT'},
 {'number': '1400',
  'name': 'Inventory - raw materials',
  'syc_code': '323',
  'syc_name': 'Matières A',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'SYCEBNL : 32 = marchandises, matières premières et fournitures liées. Matières = 323 (A) ou 324 '
            "(B) selon l'activité.",
  'gaap_section': 'CA',
  'account_type': 'STOCK'},
 {'number': '1410',
  'name': 'Inventory - work in progress',
  'syc_code': '35',
  'syc_name': 'Produits et services en cours',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Dans le SYCEBNL, 34 = dons en nature. Les produits et services en cours sont en 35.',
  'gaap_section': 'CA',
  'account_type': 'STOCK'},
 {'number': '1420',
  'name': 'Inventory - finished goods',
  'syc_code': '361',
  'syc_name': 'Produits finis A',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Produits finis : 361 (activité A) ou 362 (activité B).',
  'gaap_section': 'CA',
  'account_type': 'STOCK'},
 {'number': '1430',
  'name': 'Inventory - merchandise',
  'syc_code': '321',
  'syc_name': 'Marchandises A',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': "Marchandises : 321 (activité A) ou 322 (activité B). 31 = biens liés à l'activité.",
  'gaap_section': 'CA',
  'account_type': 'STOCK'},
 {'number': '1500',
  'name': 'Prepaid expenses',
  'syc_code': '476',
  'syc_name': "Charges constatées d'avance",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'AUTRE_ACTIF_CT'},
 {'number': '1510',
  'name': 'Prepaid insurance',
  'syc_code': '476',
  'syc_name': "Charges constatées d'avance",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CA',
  'account_type': 'AUTRE_ACTIF_CT'},
 {'number': '1600',
  'name': 'Land',
  'syc_code': '22',
  'syc_name': 'Terrains',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1610',
  'name': 'Buildings',
  'syc_code': '231',
  'syc_name': 'Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol '
              'propre',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1620',
  'name': 'Machinery and equipment',
  'syc_code': '241',
  'syc_name': 'Matériel et outillage industriel et commercial',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1630',
  'name': 'Vehicles',
  'syc_code': '245',
  'syc_name': 'Matériel de transport',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1640',
  'name': 'Furniture and fixtures',
  'syc_code': '244',
  'syc_name': 'Matériel et mobilier',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1650',
  'name': 'Computer equipment',
  'syc_code': '244',
  'syc_name': 'Matériel et mobilier',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1660',
  'name': 'Accumulated depreciation - buildings',
  'syc_code': '283',
  'syc_name': 'Amortissements des bâtiments, installations techniques et agencements',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Compte de sens inverse : coefficient 1 à valider.',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1670',
  'name': 'Accumulated depreciation - equipment',
  'syc_code': '284',
  'syc_name': 'Amortissements du matériel',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Compte de sens inverse : coefficient 1 à valider.',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1680',
  'name': 'Intangible assets',
  'syc_code': '21',
  'syc_name': 'Immobilisations incorporelles',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1690',
  'name': 'Accumulated amortization',
  'syc_code': '281',
  'syc_name': 'Amortissements des immobilisations incorporelles',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Compte de sens inverse : coefficient 1 à valider.',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1700',
  'name': 'Investments',
  'syc_code': '26',
  'syc_name': 'Titres de participation',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Libellé trop générique : titres de participation (26), autres titres immobilisés (27) ou titres '
            "de placement (50) selon l'intention.",
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '1800',
  'name': 'Accounts payable',
  'syc_code': '401',
  'syc_name': 'Fournisseurs, dettes en compte',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'COMPTES_FOURNISSEURS'},
 {'number': '1810',
  'name': 'Notes payable',
  'syc_code': '402',
  'syc_name': 'Fournisseurs, effets à payer',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1820',
  'name': 'Accrued expenses',
  'syc_code': '408',
  'syc_name': 'Fournisseurs, factures non parvenues',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1830',
  'name': 'Salaries payable',
  'syc_code': '422',
  'syc_name': 'Personnel, rémunérations dues',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1840',
  'name': 'Payroll taxes payable',
  'syc_code': '431',
  'syc_name': 'Sécurité sociale',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': "431 = organismes sociaux. Les retenues d'impôt sur salaires vont en 447.",
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1850',
  'name': 'VAT payable',
  'syc_code': '443',
  'syc_name': 'État, T.V.A. facturée',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': '443 = TVA facturée. La TVA nette à payer résulte de 443 moins 445 (TVA récupérable), soit le '
            'solde 444.',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1860',
  'name': 'Income taxes payable',
  'syc_code': '442',
  'syc_name': 'État, autres impôts et taxes',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': "Le SYCEBNL n'a pas de compte 441 (impôt sur les bénéfices). Impôts éventuels (ex. activités "
            'lucratives) : 442, à adapter.',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1870',
  'name': 'Short-term loans',
  'syc_code': '561',
  'syc_name': 'Crédits de trésorerie',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '1880',
  'name': 'Long-term debt',
  'syc_code': '182',
  'syc_name': 'Emprunts et dettes auprès des établissements de crédit',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Dans le SYCEBNL, les emprunts sont en classe 18 (et non 16, qui regroupe les fonds affectés).',
  'gaap_section': 'LTL',
  'account_type': 'PASSIF_LONG_TERME'},
 {'number': '1900',
  'name': 'Common stock',
  'syc_code': '101',
  'syc_name': 'Dotation non consomptible sans droit de reprise',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Pas de capital social. Le fonds propre est la dotation : 101 (sans droit de reprise) ou 102 '
            "(avec droit de reprise). Même numéro qu'en SYSCOHADA mais sens différent.",
  'gaap_section': 'EQ',
  'account_type': 'CAPITAUX_PROPRES'},
 {'number': '1910',
  'name': 'Additional paid-in capital',
  'syc_code': 'N/A',
  'syc_name': 'Pas de compte équivalent dans le SYCEBNL',
  'mapping_type': 'Pas de correspondance',
  'coefficient': 1.0,
  'review_status': 'Sans équivalent',
  'remark': 'Pas de prime liée au capital dans le SYCEBNL. À reclasser selon la nature (dotation, droit '
            "d'entrée 103, réserves 118).",
  'gaap_section': 'EQ',
  'account_type': 'CAPITAUX_PROPRES'},
 {'number': '1920',
  'name': 'Retained earnings',
  'syc_code': '121',
  'syc_name': 'Report à nouveau des excédents',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': '121 = report à nouveau des excédents ; 129 = report à nouveau des déficits.',
  'gaap_section': 'EQ',
  'account_type': 'CAPITAUX_PROPRES'},
 {'number': '1930',
  'name': 'Legal reserves',
  'syc_code': '112',
  'syc_name': 'Réserves statutaires ou contractuelles',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Pas de réserve légale (111 absent). Réserves statutaires ou contractuelles = 112.',
  'gaap_section': 'EQ',
  'account_type': 'CAPITAUX_PROPRES'},
 {'number': '1940',
  'name': 'Current year earnings',
  'syc_code': '13',
  'syc_name': "Résultat net de l'exercice",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': "13 : excédent (131) ou déficit (139) de l'exercice.",
  'gaap_section': 'EQ',
  'account_type': 'CAPITAUX_PROPRES'},
 {'number': '2000',
  'name': 'Sales revenue',
  'syc_code': '705',
  'syc_name': 'Ventes marchandises, services et produits finis',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'SYCEBNL : 701 = cotisations des adhérents. Les ventes sont en 705.',
  'gaap_section': 'REV',
  'account_type': 'PRODUITS'},
 {'number': '2010',
  'name': 'Service revenue',
  'syc_code': '705',
  'syc_name': 'Ventes marchandises, services et produits finis',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'SYCEBNL : 706 = revenus des manifestations. Les services vendus sont en 705.',
  'gaap_section': 'REV',
  'account_type': 'PRODUITS'},
 {'number': '2020',
  'name': 'Sales returns and allowances',
  'syc_code': '705',
  'syc_name': 'Ventes marchandises, services et produits finis',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Pas de compte 709 dans le SYCEBNL. Rabais, remises et ristournes accordés : en diminution du '
            'revenu (705).',
  'gaap_section': 'REV',
  'account_type': 'PRODUITS'},
 {'number': '2100',
  'name': 'Cost of goods sold',
  'syc_code': '603',
  'syc_name': 'Variations des stocks de biens achetés et reçus en dons en nature à distribuer',
  'mapping_type': 'Multiple / à préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'COGS',
  'account_type': 'COUT_DES_VENTES'},
 {'number': '2110',
  'name': 'Raw material expense',
  'syc_code': '602',
  'syc_name': 'Achats de marchandises, de matières premières et fournitures liées',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'COGS',
  'account_type': 'COUT_DES_VENTES'},
 {'number': '2120',
  'name': 'Purchases of merchandise',
  'syc_code': '602',
  'syc_name': 'Achats de marchandises, de matières premières et fournitures liées',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': "SYCEBNL : 601 = achats de biens et services liés à l'activité. Les achats de marchandises sont "
            'en 602.',
  'gaap_section': 'COGS',
  'account_type': 'COUT_DES_VENTES'},
 {'number': '2200',
  'name': 'Salaries and wages expense',
  'syc_code': '661',
  'syc_name': 'Rémunérations directes versées au personnel national',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2210',
  'name': 'Payroll taxes expense',
  'syc_code': '664',
  'syc_name': 'Charges sociales',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2300',
  'name': 'Rent expense',
  'syc_code': '622',
  'syc_name': 'Locations, charges locatives',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2310',
  'name': 'Utilities expense',
  'syc_code': '605',
  'syc_name': 'Autres achats',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2320',
  'name': 'Insurance expense',
  'syc_code': '625',
  'syc_name': "Primes d'assurance",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2330',
  'name': 'Advertising expense',
  'syc_code': '627',
  'syc_name': 'Publicité, publications, relations publiques',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2340',
  'name': 'Professional fees',
  'syc_code': '632',
  'syc_name': "Rémunérations d'intermédiaires et de conseils",
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2350',
  'name': 'Travel expense',
  'syc_code': '638',
  'syc_name': 'Autres charges externes',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2400',
  'name': 'Depreciation expense',
  'syc_code': '681',
  'syc_name': "Dotations aux amortissements d'exploitation",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2410',
  'name': 'Bad debt expense',
  'syc_code': '659',
  'syc_name': "Charges pour dépréciations et provisions pour risques à court terme d'exploitation",
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Perte définitive sur créance = 651 ; dotation à la dépréciation = 659 ou 691. À ventiler.',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2500',
  'name': 'Interest expense',
  'syc_code': '671',
  'syc_name': 'Intérêts des emprunts',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OEXP',
  'account_type': 'DEPENSES'},
 {'number': '2510',
  'name': 'Bank charges',
  'syc_code': '631',
  'syc_name': 'Frais bancaires',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '2600',
  'name': 'Interest income',
  'syc_code': '771',
  'syc_name': 'Intérêts de prêts et créances diverses',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OINC',
  'account_type': 'AUTRES_PRODUITS'},
 {'number': '2700',
  'name': 'Income tax expense',
  'syc_code': '641',
  'syc_name': 'Impôts et taxes directs',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': "Pas de classe 89 ni d'impôt sur les bénéfices dans le SYCEBNL. Impôts éventuels : 641 (impôts "
            'et taxes directs), à adapter.',
  'gaap_section': 'TAX',
  'account_type': 'DEPENSES'},
 {'number': '2800',
  'name': 'Gain on sale of assets',
  'syc_code': '822',
  'syc_name': "Produits des cessions d'immobilisations corporelles",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'US GAAP : gain net. SYCEBNL : produit de cession (82) et valeur comptable (81) comptabilisés '
            'séparément. Mapping non 1-pour-1.',
  'gaap_section': 'OINC',
  'account_type': 'AUTRES_PRODUITS'},
 {'number': '2810',
  'name': 'Loss on disposal of assets',
  'syc_code': '812',
  'syc_name': "Valeurs comptables des cessions d'immobilisations corporelles",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'US GAAP : perte nette. SYCEBNL : produit (82) et valeur comptable (81) séparés. Mapping non '
            '1-pour-1.',
  'gaap_section': 'OEXP',
  'account_type': 'DEPENSES'},
 {'number': '3000',
  'name': 'Other current assets',
  'syc_code': '471',
  'syc_name': 'Débiteurs et créditeurs divers',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': '471 = débiteurs et créditeurs divers.',
  'gaap_section': 'CA',
  'account_type': 'AUTRE_ACTIF_CT'},
 {'number': '3100',
  'name': 'Deposits and guarantees',
  'syc_code': '275',
  'syc_name': 'Dépôts et cautionnements versés',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '3200',
  'name': 'Deferred tax assets',
  'syc_code': 'N/A',
  'syc_name': 'Pas de compte équivalent dans le SYCEBNL',
  'mapping_type': 'Retraitement nécessaire',
  'coefficient': 1.0,
  'review_status': 'Sans équivalent',
  'remark': "Pas d'impôts différés dans le SYCEBNL en comptes individuels. Retraitement à gérer hors plan.",
  'gaap_section': 'NCA',
  'account_type': 'ACTIF_LONG_TERME'},
 {'number': '4000',
  'name': 'Unearned revenue',
  'syc_code': '477',
  'syc_name': "Produits constatés d'avance",
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '4100',
  'name': 'Customer deposits',
  'syc_code': '419',
  'syc_name': 'Adhérents, Clients-usagers créditeurs',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '4200',
  'name': 'Current portion of long-term debt',
  'syc_code': '182',
  'syc_name': 'Emprunts et dettes auprès des établissements de crédit',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': "La part à moins d'un an reste en 182 ; reclassement à faire dans la présentation du bilan.",
  'gaap_section': 'CL',
  'account_type': 'PASSIF_COURT_TERME'},
 {'number': '4300',
  'name': 'Lease liabilities',
  'syc_code': '187',
  'syc_name': 'Dettes de location-acquisition',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': '187 = dettes de location-acquisition. Les locations opérationnelles (ASC 842) ne sont pas au '
            'bilan : retraitement nécessaire.',
  'gaap_section': 'LTL',
  'account_type': 'PASSIF_LONG_TERME'},
 {'number': '4400',
  'name': 'Deferred tax liabilities',
  'syc_code': 'N/A',
  'syc_name': 'Pas de compte équivalent dans le SYCEBNL',
  'mapping_type': 'Retraitement nécessaire',
  'coefficient': 1.0,
  'review_status': 'Sans équivalent',
  'remark': "Pas d'impôts différés dans le SYCEBNL en comptes individuels. Retraitement à gérer hors plan.",
  'gaap_section': 'LTL',
  'account_type': 'PASSIF_LONG_TERME'},
 {'number': '4500',
  'name': 'Provisions for litigation',
  'syc_code': '191',
  'syc_name': 'Provisions pour litiges',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': '191 = provisions pour litiges.',
  'gaap_section': 'LTL',
  'account_type': 'PASSIF_LONG_TERME'},
 {'number': '5000',
  'name': 'Purchases of raw materials',
  'syc_code': '602',
  'syc_name': 'Achats de marchandises, de matières premières et fournitures liées',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '602 = achats de marchandises, matières premières et fournitures liées. Doublon fonctionnel avec '
            '2110 et 2120.',
  'gaap_section': 'COGS',
  'account_type': 'COUT_DES_VENTES'},
 {'number': '5100',
  'name': 'Freight and delivery expense',
  'syc_code': '612',
  'syc_name': 'Transports sur ventes',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Modifié',
  'remark': 'Pas de compte 611 dans le SYCEBNL. 612 = transports sur ventes (fret sortant). Le fret entrant '
            "est inclus dans le coût d'achat (602) ou en 618.",
  'gaap_section': 'COGS',
  'account_type': 'COUT_DES_VENTES'},
 {'number': '5200',
  'name': 'Repairs and maintenance',
  'syc_code': '624',
  'syc_name': 'Entretien, réparation, remise en état et maintenance',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '5300',
  'name': 'Office supplies',
  'syc_code': '604',
  'syc_name': 'Achats stockés de matières et fournitures consommables',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '5400',
  'name': 'Telephone and internet',
  'syc_code': '628',
  'syc_name': 'Frais de télécommunications',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'},
 {'number': '5500',
  'name': 'Foreign exchange loss',
  'syc_code': '676',
  'syc_name': 'Pertes de change financières',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OEXP',
  'account_type': 'DEPENSES'},
 {'number': '5600',
  'name': 'Foreign exchange gain',
  'syc_code': '776',
  'syc_name': 'Gains de change financiers',
  'mapping_type': 'Directe',
  'coefficient': 1.0,
  'review_status': 'À confirmer',
  'remark': 'Distinct de 2600 désormais (intérêts en 771). Gains de change = 776.',
  'gaap_section': 'OINC',
  'account_type': 'AUTRES_PRODUITS'},
 {'number': '5700',
  'name': 'Dividend income',
  'syc_code': '772',
  'syc_name': 'Revenus de participations et autres titres immobilisés',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OINC',
  'account_type': 'AUTRES_PRODUITS'},
 {'number': '5800',
  'name': 'Other operating income',
  'syc_code': '758',
  'syc_name': 'Produits divers',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OINC',
  'account_type': 'AUTRES_PRODUITS'},
 {'number': '5900',
  'name': 'Other operating expenses',
  'syc_code': '658',
  'syc_name': 'Charges diverses',
  'mapping_type': 'À préciser',
  'coefficient': 1.0,
  'review_status': 'Inchangé',
  'remark': '',
  'gaap_section': 'OPEX',
  'account_type': 'DEPENSES'}]
